# ########################
# FUNCTION THAT RETURNS A LIST OF ALL THE 
# PREPROCESSING FUNCTIONS ACCORDING TO THE PREPROCESSING.YAML FILE

# #########################
# FUNCTION THAT RETURNS A LIST OF ALL THE 
# AUGMENTATION FUNCTIONS ACCORDING TO THE AUGMENTATION.YAML FILE

# ###########################
# FUNCTION THAT CONCATENATES THE LISTS OF THE
# PREPROCESSING AND THE AUGMENTATIONS FUNCTIONS (IF ANY)
# WITH THE NORMALIZE FUNCTION AND RETURNS
# THE TRANSFORM COMPOSE OF THE RESULTING LIST